### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by tomatoFQ** [google/ios-webkit-debug-proxy#325]
Anyone help me...
`PS D:\software\scoop> ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
Listing devices on :9221
Connected :9222 to iPhone8p (5b64cc67a412236893af14edde7dec149a9245ce)
Invalid HTTP header
Invalid HTTP header`

win10 + IOS 12.2

**Comment by artygus** [comment]
hi @tomatoFQ, could you plase provide an output of same comand but with `-d` flag. please upload it as an attachment or a gist

**Comment by tomatoFQ** [comment]
[ios_webkit_debug_proxy.log](https://github.com/google/ios-webkit-debug-proxy/files/3572407/ios_webkit_debug_proxy.log)
@artygus I'm chinese developer.I have to use shadowsocks to reach google.com. This may be the reason?thanks for your help.

**Comment by arifhussain353** [comment]
@artygus  any update? I am facing the same issue. Terminal showing me `Invalid HTTP header`

**Comment by artygus** [comment]
@arifhussain353 do you also behind firewall?

**Comment by BenjaminSchilller** [comment]
@artygus same issue, but I'm not behind firewall.

my test log > [test.log](https://github.com/google/ios-webkit-debug-proxy/files/4504666/test.log)

Thank you for the support!

**Comment by artygus** [comment]
@BenjaminSchilller thanks for the log, I'll take a look, hopefully over the weekend

**Comment by BenjaminSchilller** [comment]
@artygus thanks. I will test, if you push a new version.

**Comment by miccoh1994** [comment]
same issue on Mac with Iphone 8. attached is my output log
[test.log](https://github.com/google/ios-webkit-debug-proxy/files/6101362/test.log)

**Comment by miccoh1994** [comment]
I tried on Windows and Ubuntu and I experience the same issue

**Comment by artygus** [comment]
@miccoh1994 thanks for the new log I'll check it out. I didn't find anything suspicious last time 🤔 assumed it's local network issues

**Comment by miccoh1994** [comment]
It could be that I am using a 4G/LTE router while I wait for my ISP to install my fibre. I will try again tomorrow and let you know, could be that the router is misconfigured or something and it is an internal network problem.

**Comment by BenjaminSchilller** [comment]
@miccoh1994 : I have a internal network with Fritzbox 192.168.178.xxx and it's also a problem there - just as info.

**Comment by ndunks** [comment]
Facing same problem on chrome `Remote Devices` list, but fixed now. in my case, the problem is because I have proxied setings in discover network targets:
- chrome://inspect/#devices
- Discover network targets (checked)
- has localhost:9221

Because port 9221 is a listing devices port not a target device port, change it to device port that displayed when you start `ios_webkit_debug_proxy`, in my case is `9222` so I change to `localhost:9222` and it worked as expected (using chrome devtools).

**Comment by miccoh1994** [comment]
So I have tried a variety of routers and on MacOS, Windows 10, and Ubuntu. Problem persists. I just used a my macbook with Safari to debug as my issues were not Chrome related.
